// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var TestEnMd = require("../content/test.en.md");
var TestFrMd = require("../content/test.fr.md");

var test_en = TestEnMd;

var test_fr = TestFrMd;

var test = /* record */[
  /* en */test_en,
  /* fr */test_fr
];

exports.test_en = test_en;
exports.test_fr = test_fr;
exports.test = test;
/* test_en Not a pure module */
