// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function Translate(M) {
  var to_str = function (language, item) {
    if (language) {
      return Curry._1(M[/* to_i18n_text */0], item)[/* fr */1];
    } else {
      return Curry._1(M[/* to_i18n_text */0], item)[/* en */0];
    }
  };
  var react_string = to_str;
  return /* module */[
          /* to_i18n_text */M[0],
          /* to_str */to_str,
          /* react_string */react_string
        ];
}

exports.Translate = Translate;
/* No side effect */
