// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var ctx = React.createContext(/* EN */0);

function makeProps(language, children, param) {
  return {
          value: language,
          children: children
        };
}

var make = ctx.Provider;

exports.ctx = ctx;
exports.makeProps = makeProps;
exports.make = make;
/* ctx Not a pure module */
