// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function PageNotFound(Props) {
  return React.createElement("h1", undefined, "Page not found!");
}

var make = PageNotFound;

exports.make = make;
/* react Not a pure module */
