// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Strings$OurPolitics = require("./Strings.bs.js");
var LanguageContext$OurPolitics = require("./LanguageContext.bs.js");
var PolicyModalDispatch$OurPolitics = require("./PolicyModalDispatch.bs.js");

function PolicyPoint(Props) {
  var policy = Props.policy;
  var language = React.useContext(LanguageContext$OurPolitics.ctx);
  var dispatch = React.useContext(PolicyModalDispatch$OurPolitics.ctx);
  var t = Curry._1(Strings$OurPolitics.$$Text[/* react_string */2], language);
  return React.createElement("li", {
              className: "policyPoint"
            }, React.createElement("a", {
                  className: "policyPoint--link",
                  onClick: (function (param) {
                      return Curry._1(dispatch, /* ModalOpen */[policy]);
                    })
                }, Curry._1(t, policy[/* summary */2])));
}

var make = PolicyPoint;

exports.make = make;
/* react Not a pure module */
