// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var ctx = React.createContext((function (param) {
        return /* () */0;
      }));

function makeProps(dispatch, children, param) {
  return {
          value: dispatch,
          children: children
        };
}

var make = ctx.Provider;

exports.ctx = ctx;
exports.makeProps = makeProps;
exports.make = make;
/* ctx Not a pure module */
