// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Schema$OurPolitics = require("./schema.bs.js");
var Strings$OurPolitics = require("./Strings.bs.js");
var PolicyRow$OurPolitics = require("./PolicyRow.bs.js");
var LanguageContext$OurPolitics = require("./LanguageContext.bs.js");

function PolicyTable(Props) {
  var data = Props.data;
  var policyRows = $$Array.of_list(Curry._3(Schema$OurPolitics.TopicMap[/* fold */10], (function (topic, policies, lst) {
              return /* :: */[
                      React.createElement(PolicyRow$OurPolitics.make, {
                            topic: topic,
                            policies: policies,
                            key: Curry._2(Strings$OurPolitics.Topic[/* to_str */1], /* EN */0, topic)
                          }),
                      lst
                    ];
            }), data, /* [] */0));
  var language = React.useContext(LanguageContext$OurPolitics.ctx);
  var t = Curry._1(Strings$OurPolitics.$$Text[/* react_string */2], language);
  var t_party = Curry._1(Strings$OurPolitics.Party[/* react_string */2], language);
  return React.createElement("div", {
              className: "policyTable"
            }, React.createElement("div", {
                  className: "policyRow tableHeader"
                }, React.createElement("div", {
                      className: "policyCells"
                    }, React.createElement("div", {
                          className: "policyCell partyTitle backgroundColor--Empty"
                        }, Curry._1(t, Strings$OurPolitics.title)), React.createElement("div", {
                          className: "policyCell partyTitle backgroundColor--NDP"
                        }, Curry._1(t_party, /* NDP */2)), React.createElement("div", {
                          className: "policyCell partyTitle backgroundColor--Conservatives"
                        }, Curry._1(t_party, /* Conservative */1)), React.createElement("div", {
                          className: "policyCell partyTitle backgroundColor--Liberals"
                        }, Curry._1(t_party, /* Liberal */0)))), React.createElement("ul", undefined, policyRows));
}

var make = PolicyTable;

exports.make = make;
/* react Not a pure module */
