// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$OurPolitics = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(App$OurPolitics.make, { }), "page-root");

/*  Not a pure module */
