// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var compare = Caml_obj.caml_compare;

var TopicMap = $$Map.Make(/* module */[/* compare */compare]);

exports.TopicMap = TopicMap;
/* TopicMap Not a pure module */
