// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function SplashIndex(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Hello world!"), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("a", {
                          href: "#",
                          onClick: (function (param) {
                              return ReasonReactRouter.push("/policies");
                            })
                        }, "Policies (2019)"))));
}

var make = SplashIndex;

exports.make = make;
/* react Not a pure module */
