// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var I18n$OurPolitics = require("./I18n.bs.js");

function to_i18n_text(text) {
  return text;
}

var $$Text = I18n$OurPolitics.Translate(/* module */[/* to_i18n_text */to_i18n_text]);

function to_i18n_text$1(lang) {
  return /* record */[
          /* en */"en",
          /* fr */"fr"
        ];
}

var Language = I18n$OurPolitics.Translate(/* module */[/* to_i18n_text */to_i18n_text$1]);

function to_i18n_text$2(party) {
  switch (party) {
    case 0 : 
        return /* record */[
                /* en */"Liberals",
                /* fr */"Libéral"
              ];
    case 1 : 
        return /* record */[
                /* en */"Conservatives",
                /* fr */"Conservateur"
              ];
    case 2 : 
        return /* record */[
                /* en */"NDP",
                /* fr */"NPD"
              ];
    case 3 : 
        return /* record */[
                /* en */"Green",
                /* fr */"Vert"
              ];
    
  }
}

var Party = I18n$OurPolitics.Translate(/* module */[/* to_i18n_text */to_i18n_text$2]);

function to_i18n_text$3(topic) {
  switch (topic) {
    case 0 : 
        return /* record */[
                /* en */"Families",
                /* fr */"?"
              ];
    case 1 : 
        return /* record */[
                /* en */"Foreign Policy",
                /* fr */"?"
              ];
    case 2 : 
        return /* record */[
                /* en */"Taxes",
                /* fr */"?"
              ];
    case 3 : 
        return /* record */[
                /* en */"International Trade",
                /* fr */"?"
              ];
    case 4 : 
        return /* record */[
                /* en */"Environment",
                /* fr */"?"
              ];
    case 5 : 
        return /* record */[
                /* en */"Government",
                /* fr */"?"
              ];
    case 6 : 
        return /* record */[
                /* en */"Indigenous Relations",
                /* fr */"?"
              ];
    case 7 : 
        return /* record */[
                /* en */"Healthcare",
                /* fr */"?"
              ];
    case 8 : 
        return /* record */[
                /* en */"Infrastructure",
                /* fr */"?"
              ];
    case 9 : 
        return /* record */[
                /* en */"Science",
                /* fr */"?"
              ];
    
  }
}

var Topic = I18n$OurPolitics.Translate(/* module */[/* to_i18n_text */to_i18n_text$3]);

var title = /* record */[
  /* en */"Topics",
  /* fr */"Sujets"
];

var no_policy_listed = /* record */[
  /* en */"No policy",
  /* fr */"Absence de politique"
];

exports.title = title;
exports.no_policy_listed = no_policy_listed;
exports.$$Text = $$Text;
exports.Language = Language;
exports.Party = Party;
exports.Topic = Topic;
/* Text Not a pure module */
