// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function dangerousHtml(html) {
  return {
          __html: html
        };
}

exports.dangerousHtml = dangerousHtml;
/* No side effect */
